
#Breeding Recipes Configuration
[breeding]

	[breeding.vanilla]
		beeSpawnEgg = "minecraft:bee_spawn_egg"
		catSpawnEgg = "minecraft:cat_spawn_egg"
		chickenSpawnEgg = "minecraft:chicken_spawn_egg"
		cowSpawnEgg = "minecraft:cow_spawn_egg"
		donkeySpawnEgg = "minecraft:donkey_spawn_egg"
		foxSpawnEgg = "minecraft:fox_spawn_egg"
		goatSpawnEgg = "minecraft:goat_spawn_egg"
		hoglinSpawnEgg = "minecraft:hoglin_spawn_egg"
		horseSpawnEgg = "minecraft:horse_spawn_egg"
		llamaSpawnEgg = "minecraft:llama_spawn_egg"
		mooshroomSpawnEgg = "minecraft:mooshroom_spawn_egg"
		ocelotSpawnEgg = "minecraft:ocelot_spawn_egg"
		pandaSpawnEgg = "minecraft:panda_spawn_egg"
		pigSpawnEgg = "minecraft:pig_spawn_egg"
		rabbitSpawnEgg = "minecraft:rabbit_spawn_egg"
		sheepSpawnEgg = "minecraft:sheep_spawn_egg"
		striderSpawnEgg = "minecraft:strider_spawn_egg"
		trader_llamaSpawnEgg = "minecraft:trader_llama_spawn_egg"
		turtleSpawnEgg = "minecraft:turtle_spawn_egg"
		#Egg that turtle lays after breeding
		turtleeggResult = "minecraft:turtle_egg"
		#Min amount of eggs that turtle lays after breeding
		#Range: 1 ~ 64
		turtleEggMinAmount = 1
		#Max amount of eggs that turtle lays after breeding
		#Range: 1 ~ 64
		turtleEggMaxAmount = 4
		wolfSpawnEgg = "minecraft:wolf_spawn_egg"

		[breeding.vanilla.bee]
			#Ingredients required for bee breeding
			beeIngredients = "#minecraft:flowers"

		[breeding.vanilla.cat]
			#Ingredients required for cat breeding
			catIngredients = "minecraft:cod, minecraft:salmon"

		[breeding.vanilla.chicken]
			#Ingredients required for chicken breeding
			chickenIngredients = "minecraft:wheat_seeds, minecraft:pumpkin_seeds, minecraft:melon_seeds, minecraft:beetroot_seeds, minecraft:torchflower_seeds, minecraft:pitcher_pod"

		[breeding.vanilla.cow]
			#Ingredients required for cow breeding
			cowIngredients = "minecraft:wheat"

		[breeding.vanilla.donkey]
			#Ingredients required for donkey breeding
			donkeyIngredients = "minecraft:golden_apple, minecraft:enchanted_golden_apple, minecraft:golden_carrot"

		[breeding.vanilla.fox]
			#Ingredients required for fox breeding
			foxIngredients = "minecraft:sweet_berries, minecraft:glow_berries"

		[breeding.vanilla.goat]
			#Ingredients required for goat breeding
			goatIngredients = "minecraft:wheat"

		[breeding.vanilla.hoglin]
			#Ingredients required for hoglin breeding
			hoglinIngredients = "minecraft:crimson_fungus"

		[breeding.vanilla.horse]
			#Ingredients required for horse breeding
			horseIngredients = "minecraft:golden_apple, minecraft:enchanted_golden_apple, minecraft:golden_carrot"

		[breeding.vanilla.llama]
			#Ingredients required for llama breeding
			llamaIngredients = "minecraft:hay_block"

		[breeding.vanilla.mooshroom]
			#Ingredients required for mooshroom breeding
			mooshroomIngredients = "minecraft:wheat"

		[breeding.vanilla.ocelot]
			#Ingredients required for ocelot breeding
			ocelotIngredients = "minecraft:cod, minecraft:salmon"

		[breeding.vanilla.panda]
			#Ingredients required for panda breeding
			pandaIngredients = "minecraft:bamboo"

		[breeding.vanilla.pig]
			#Ingredients required for pig breeding
			pigIngredients = "minecraft:carrot, minecraft:potato, minecraft:beetroot"

		[breeding.vanilla.rabbit]
			#Ingredients required for rabbit breeding
			rabbitIngredients = "minecraft:dandelion, minecraft:carrot, minecraft:golden_carrot"

		[breeding.vanilla.sheep]
			#Ingredients required for sheep breeding
			sheepIngredients = "minecraft:wheat"

		[breeding.vanilla.strider]
			#Ingredients required for strider breeding
			striderIngredients = "minecraft:warped_fungus"

		[breeding.vanilla.trader_llama]
			#Ingredients required for trader_llama breeding
			trader_llamaIngredients = "minecraft:hay_block"

		[breeding.vanilla.turtle]
			#Ingredients required for turtle breeding
			turtleIngredients = "minecraft:seagrass"

		[breeding.vanilla.wolf]
			#Ingredients required for wolf breeding
			wolfIngredients = "minecraft:porkchop, minecraft:cooked_porkchop, minecraft:beef, minecraft:cooked_beef, minecraft:chicken, minecraft:cooked_chicken, minecraft:rotten_flesh, minecraft:rabbit, minecraft:cooked_rabbit, minecraft:mutton, minecraft:cooked_mutton"

	[breeding.integration]

		[breeding.integration.alexsmobs]
			alligator_snapping_turtleSpawnEgg = "alexsmobs:spawn_egg_alligator_snapping_turtle"
			anacondaSpawnEgg = "alexsmobs:spawn_egg_anaconda"
			anteaterSpawnEgg = "alexsmobs:spawn_egg_anteater"
			bald_eagleSpawnEgg = "alexsmobs:spawn_egg_bald_eagle"
			banana_slugSpawnEgg = "alexsmobs:spawn_egg_banana_slug"
			bisonSpawnEgg = "alexsmobs:spawn_egg_bison"
			blue_jaySpawnEgg = "alexsmobs:spawn_egg_blue_jay"
			capuchin_monkeySpawnEgg = "alexsmobs:spawn_egg_capuchin_monkey"
			cockroachSpawnEgg = "alexsmobs:spawn_egg_cockroach"
			crocodileSpawnEgg = "alexsmobs:spawn_egg_crocodile"
			crowSpawnEgg = "alexsmobs:spawn_egg_crow"
			emuSpawnEgg = "alexsmobs:spawn_egg_emu"
			endergradeSpawnEgg = "alexsmobs:spawn_egg_endergrade"
			flutterSpawnEgg = "alexsmobs:spawn_egg_flutter"
			flySpawnEgg = "alexsmobs:spawn_egg_fly"
			gazelleSpawnEgg = "alexsmobs:spawn_egg_gazelle"
			gelada_monkeySpawnEgg = "alexsmobs:spawn_egg_gelada_monkey"
			hummingbirdSpawnEgg = "alexsmobs:spawn_egg_hummingbird"
			jerboaSpawnEgg = "alexsmobs:spawn_egg_jerboa"
			kangarooSpawnEgg = "alexsmobs:spawn_egg_kangaroo"
			laviathanSpawnEgg = "alexsmobs:spawn_egg_laviathan"
			maned_wolfSpawnEgg = "alexsmobs:spawn_egg_maned_wolf"
			mantis_shrimpSpawnEgg = "alexsmobs:spawn_egg_mantis_shrimp"
			mimic_octopusSpawnEgg = "alexsmobs:spawn_egg_mimic_octopus"
			mudskipperSpawnEgg = "alexsmobs:spawn_egg_mudskipper"
			mungusSpawnEgg = "alexsmobs:spawn_egg_mungus"
			orcaSpawnEgg = "alexsmobs:spawn_egg_orca"
			platypusSpawnEgg = "alexsmobs:spawn_egg_platypus"
			potooSpawnEgg = "alexsmobs:spawn_egg_potoo"
			raccoonSpawnEgg = "alexsmobs:spawn_egg_raccoon"
			rattlesnakeSpawnEgg = "alexsmobs:spawn_egg_rattlesnake"
			rhinocerosSpawnEgg = "alexsmobs:spawn_egg_rhinoceros"
			roadrunnerSpawnEgg = "alexsmobs:spawn_egg_roadrunner"
			seagullSpawnEgg = "alexsmobs:spawn_egg_seagull"
			sealSpawnEgg = "alexsmobs:spawn_egg_seal"
			skunkSpawnEgg = "alexsmobs:spawn_egg_skunk"
			snow_leopardSpawnEgg = "alexsmobs:spawn_egg_snow_leopard"
			sugar_gliderSpawnEgg = "alexsmobs:spawn_egg_sugar_glider"
			tasmanian_devilSpawnEgg = "alexsmobs:spawn_egg_tasmanian_devil"
			terrapinSpawnEgg = "alexsmobs:spawn_egg_terrapin"
			tigerSpawnEgg = "alexsmobs:spawn_egg_tiger"
			toucanSpawnEgg = "alexsmobs:spawn_egg_toucan"
			tusklinSpawnEgg = "alexsmobs:spawn_egg_tusklin"

			[breeding.integration.alexsmobs.alligator_snapping_turtle]
				#Ingredients required for alligator_snapping_turtle breeding
				alligator_snapping_turtleIngredients = "minecraft:cod"

			[breeding.integration.alexsmobs.anaconda]
				#Ingredients required for anaconda breeding
				anacondaIngredients = "minecraft:chicken, minecraft:cooked_chicken"

			[breeding.integration.alexsmobs.anteater]
				#Ingredients required for anteater breeding
				anteaterIngredients = "alexsmobs:leafcutter_ant_pupa"

			[breeding.integration.alexsmobs.bald_eagle]
				#Ingredients required for bald_eagle breeding
				bald_eagleIngredients = "minecraft:rotten_flesh"

			[breeding.integration.alexsmobs.banana_slug]
				#Ingredients required for banana_slug breeding
				banana_slugIngredients = "minecraft:brown_mushroom"

			[breeding.integration.alexsmobs.bison]
				#Ingredients required for bison breeding
				bisonIngredients = "minecraft:wheat"

			[breeding.integration.alexsmobs.blue_jay]
				#Ingredients required for blue_jay breeding
				blue_jayIngredients = "#alexsmobs:insect_items"

			[breeding.integration.alexsmobs.capuchin_monkey]
				#Ingredients required for capuchin_monkey breeding
				capuchin_monkeyIngredients = "#alexsmobs:insect_items"

			[breeding.integration.alexsmobs.cockroach]
				#Ingredients required for cockroach breeding
				cockroachIngredients = "minecraft:sugar"

			[breeding.integration.alexsmobs.crocodile]
				#Ingredients required for crocodile breeding
				crocodileIngredients = "minecraft:rotten_flesh"
				#Egg that crocodile lays after breeding
				crocodileeggResult = "alexsmobs:crocodile_egg"
				#Min amount of eggs that crocodile lays after breeding
				#Range: 1 ~ 64
				crocodileEggMinAmount = 1
				#Max amount of eggs that crocodile lays after breeding
				#Range: 1 ~ 64
				crocodileEggMaxAmount = 1

			[breeding.integration.alexsmobs.crow]
				#Ingredients required for crow breeding
				crowIngredients = "minecraft:pumpkin_seeds"

			[breeding.integration.alexsmobs.emu]
				#Ingredients required for emu breeding
				emuIngredients = "minecraft:wheat"

			[breeding.integration.alexsmobs.endergrade]
				#Ingredients required for endergrade breeding
				endergradeIngredients = "minecraft:chorus_fruit"

			[breeding.integration.alexsmobs.flutter]
				#Ingredients required for flutter breeding
				flutterIngredients = "minecraft:bone_meal"

			[breeding.integration.alexsmobs.fly]
				#Ingredients required for fly breeding
				flyIngredients = "minecraft:rotten_flesh"

			[breeding.integration.alexsmobs.gazelle]
				#Ingredients required for gazelle breeding
				gazelleIngredients = "minecraft:wheat"

			[breeding.integration.alexsmobs.gelada_monkey]
				#Ingredients required for gelada_monkey breeding
				gelada_monkeyIngredients = "minecraft:dead_bush"

			[breeding.integration.alexsmobs.hummingbird]
				#Ingredients required for hummingbird breeding
				hummingbirdIngredients = "#minecraft:flowers"

			[breeding.integration.alexsmobs.jerboa]
				#Ingredients required for jerboa breeding
				jerboaIngredients = "alexsmobs:maggot"

			[breeding.integration.alexsmobs.kangaroo]
				#Ingredients required for kangaroo breeding
				kangarooIngredients = "minecraft:dead_bush, minecraft:grass"

			[breeding.integration.alexsmobs.laviathan]
				#Ingredients required for laviathan breeding
				laviathanIngredients = "alexsmobs:mosquito_larva"

			[breeding.integration.alexsmobs.maned_wolf]
				#Ingredients required for maned_wolf breeding
				maned_wolfIngredients = "minecraft:chicken, minecraft:cooked_chicken, minecraft:cooked_rabbit, minecraft:rabbit"

			[breeding.integration.alexsmobs.mantis_shrimp]
				#Ingredients required for mantis_shrimp breeding
				mantis_shrimpIngredients = "alexsmobs:cooked_lobster_tail, alexsmobs:lobster_tail"

			[breeding.integration.alexsmobs.mimic_octopus]
				#Ingredients required for mimic_octopus breeding
				mimic_octopusIngredients = "minecraft:tropical_fish"

			[breeding.integration.alexsmobs.mudskipper]
				#Ingredients required for mudskipper breeding
				mudskipperIngredients = "alexsmobs:cooked_lobster_tail, alexsmobs:lobster_tail, alexsmobs:mosquito_larva"

			[breeding.integration.alexsmobs.mungus]
				#Ingredients required for mungus breeding
				mungusIngredients = "alexsmobs:mungal_spores"

			[breeding.integration.alexsmobs.orca]
				#Ingredients required for orca breeding
				orcaIngredients = "minecraft:salmon"

			[breeding.integration.alexsmobs.platypus]
				#Ingredients required for platypus breeding
				platypusIngredients = "alexsmobs:cooked_lobster_tail, alexsmobs:lobster_tail"

			[breeding.integration.alexsmobs.potoo]
				#Ingredients required for potoo breeding
				potooIngredients = "#alexsmobs:insect_items"

			[breeding.integration.alexsmobs.raccoon]
				#Ingredients required for raccoon breeding
				raccoonIngredients = "minecraft:bread"

			[breeding.integration.alexsmobs.rattlesnake]
				#Ingredients required for rattlesnake breeding
				rattlesnakeIngredients = "minecraft:porkchop, minecraft:cooked_porkchop, minecraft:beef, minecraft:cooked_beef, minecraft:chicken, minecraft:cooked_chicken, minecraft:rotten_flesh, minecraft:rabbit, minecraft:cooked_rabbit, minecraft:mutton, minecraft:cooked_mutton"

			[breeding.integration.alexsmobs.rhinoceros]
				#Ingredients required for rhinoceros breeding
				rhinocerosIngredients = "minecraft:dead_bush"

			[breeding.integration.alexsmobs.roadrunner]
				#Ingredients required for roadrunner breeding
				roadrunnerIngredients = "#alexsmobs:insect_items"

			[breeding.integration.alexsmobs.seagull]
				#Ingredients required for seagull breeding
				seagullIngredients = "minecraft:cod"

			[breeding.integration.alexsmobs.seal]
				#Ingredients required for seal breeding
				sealIngredients = "alexsmobs:lobster_tail"

			[breeding.integration.alexsmobs.skunk]
				#Ingredients required for skunk breeding
				skunkIngredients = "minecraft:sweet_berries"

			[breeding.integration.alexsmobs.snow_leopard]
				#Ingredients required for snow_leopard breeding
				snow_leopardIngredients = "alexsmobs:cooked_moose_ribs, alexsmobs:moose_ribs"

			[breeding.integration.alexsmobs.sugar_glider]
				#Ingredients required for sugar_glider breeding
				sugar_gliderIngredients = "minecraft:honeycomb"

			[breeding.integration.alexsmobs.tasmanian_devil]
				#Ingredients required for tasmanian_devil breeding
				tasmanian_devilIngredients = "minecraft:porkchop, minecraft:cooked_porkchop, minecraft:beef, minecraft:cooked_beef, minecraft:chicken, minecraft:cooked_chicken, minecraft:rabbit, minecraft:cooked_rabbit, minecraft:mutton, minecraft:cooked_mutton"

			[breeding.integration.alexsmobs.terrapin]
				#Ingredients required for terrapin breeding
				terrapinIngredients = "minecraft:seagrass"
				#Egg that terrapin lays after breeding
				terrapineggResult = "alexsmobs:terrapin_egg"
				#Min amount of eggs that terrapin lays after breeding
				#Range: 1 ~ 64
				terrapinEggMinAmount = 1
				#Max amount of eggs that terrapin lays after breeding
				#Range: 1 ~ 64
				terrapinEggMaxAmount = 4

			[breeding.integration.alexsmobs.tiger]
				#Ingredients required for tiger breeding
				tigerIngredients = "#alexsmobs:tiger_breedables"

			[breeding.integration.alexsmobs.toucan]
				#Ingredients required for toucan breeding
				toucanIngredients = "minecraft:egg"

			[breeding.integration.alexsmobs.tusklin]
				#Ingredients required for tusklin breeding
				tusklinIngredients = "minecraft:red_mushroom"

		[breeding.integration.aquaculture]
			arrau_turtleSpawnEgg = "aquaculture:arrau_turtle_spawn_egg"
			box_turtleSpawnEgg = "aquaculture:box_turtle_spawn_egg"
			starshell_turtleSpawnEgg = "aquaculture:starshell_turtle_spawn_egg"

			[breeding.integration.aquaculture.arrau_turtle]
				#Ingredients required for arrau_turtle breeding
				arrau_turtleIngredients = "#aquaculture:turtle_edible"

			[breeding.integration.aquaculture.box_turtle]
				#Ingredients required for box_turtle breeding
				box_turtleIngredients = "#aquaculture:turtle_edible"

			[breeding.integration.aquaculture.starshell_turtle]
				#Ingredients required for starshell_turtle breeding
				starshell_turtleIngredients = "#aquaculture:turtle_edible"

